version: "3.8"

services:
  app:
    build: .
    command: python3 manage.py runserver 0.0.0.0:${PORT}
    image: django-store
    restart: always
    environment:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - django-store
    depends_on:
      - redis
      - celery
  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_EXPOSED}:${POSTGRES_PORT}"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - django-store
  redis:
    image: redis:7-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./redis:/data
    depends_on:
      - db
    networks:
      - django-store
  celery:
    image: django-store
    build: .
    command: celery -A store worker -l INFO
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - django-store
networks:
  django-store:
    name: "django-store"
    driver: bridge
